package de.danoeh.antennapod.wear;

import org.greenrobot.eventbus.meta.SubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfoIndex;

/**
 * EventBus index for Wear OS app.
 * This is a placeholder - actual index will be generated by EventBus annotation processor.
 */
@SuppressWarnings({"unused", "unchecked"})
public class ApWearEventBusIndex implements SubscriberInfoIndex {
    
    private static final java.util.Map<Class<?>, SubscriberInfo> SUBSCRIBER_INDEX;

    static {
        SUBSCRIBER_INDEX = new java.util.HashMap<Class<?>, SubscriberInfo>();
    }

    @Override
    public SubscriberInfo getSubscriberInfo(Class<?> subscriberClass) {
        SubscriberInfo info = SUBSCRIBER_INDEX.get(subscriberClass);
        if (info != null) {
            return info;
        } else {
            return null;
        }
    }
}
